name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  cleanup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'published'

      - name: Cleanup published branch
        run: |
          git rm -rf .
          git clean -fdx
          git commit -m "Cleanup published branch" || echo "No changes to commit"
          git push

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Slidev presentation
        run: npm run build -- --out docs --base /commentable-for-slidev

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: published
          keep_files: false
